# -*- coding: utf-8 -*-
#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.

web:
  restart: "always"
  build: .
  #command: /bin/bash -c "gunicorn invenio_app.wsgi --workers=4 --worker-class=meinheld.gmeinheld.MeinheldWorker -b 0.0.0.0:5000 && celery worker -A invenio_app.celery"
  command: /bin/bash -c "uwsgi --ini /code/scripts/uwsgi.ini"
  #command: /bin/bash -c "invenio run -h 0.0.0.0 && celery worker -A invenio_app.celery"
  environment:
    - PATH=/home/invenio/.virtualenvs/invenio/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
    - INVENIO_WEB_HOST=127.0.0.1
    - INVENIO_WEB_INSTANCE=invenio
    - INVENIO_WEB_VENV=invenio
    - INVENIO_USER_EMAIL=info@inveniosoftware.org
    - INVENIO_USER_PASS=uspass123
    - INVENIO_POSTGRESQL_HOST=postgresql
    - INVENIO_POSTGRESQL_DBNAME=invenio
    - INVENIO_POSTGRESQL_DBUSER=invenio
    - INVENIO_POSTGRESQL_DBPASS=dbpass123
    - INVENIO_REDIS_HOST=redis
    - INVENIO_ELASTICSEARCH_HOST=elasticsearch
    - INVENIO_RABBITMQ_HOST=rabbitmq
    - INVENIO_WORKER_HOST=127.0.0.1
    - INVENIO_FILES_LOCATION_NAME=local
    - INVENIO_FILES_LOCATION_URI=/var/tmp
    - INVENIO_ROLE_SYSTEM=System Administrator
    - INVENIO_ROLE_REPOSITORY=Repository Administrator
    - INVENIO_ROLE_CONTRIBUTOR=Contributor
    - FLASK_DEBUG=1
  volumes_from:
    - static
  links:
    - postgresql
    - redis
    - elasticsearch
    - rabbitmq
  ports:
    - "5006:5000"

postgresql:
  restart: "always"
  image: postgres
  environment:
    - POSTGRES_USER=invenio
    - POSTGRES_DB=invenio
    - POSTGRES_PASSWORD=dbpass123
  ports:
    - "25406:5432"

redis:
  restart: "always"
  image: redis
  ports:
    - "26306:6379"

elasticsearch:
  restart: "always"
  build: .
  dockerfile: ./elasticsearch/Dockerfile
  ports:
    - "29206:9200"
    - "29306:9300"

rabbitmq:
  restart: "always"
  image: rabbitmq
  ports:
    - "24306:4369"
    - "45606:25672"

nginx:
  restart: "always"
  build: ./nginx
  ports:
    - "8006:80"
    - "4436:443"
  volumes_from:
    - static
  links:
    - web

static:
  restart: "no"
  build: .
  volumes:
    - /home/invenio/.virtualenvs/invenio/var/instance/static
    - /code/modules/invenio-files-rest/invenio_files_rest.egg-info
    - /code/modules/invenio-oaiserver/invenio_oaiserver.egg-info
    - /code/modules/weko-theme/weko_theme.egg-info
    - /code/modules/weko-itemtypes-ui/weko_itemtypes_ui.egg-info
    - /code/modules/weko-items-ui/weko_items_ui.egg-info
    - /code/modules/weko-accounts/weko_accounts.egg-info
    - /code/modules/weko-admin/weko_admin.egg-info
    - /code/modules/weko-logging/weko_logging.egg-info
    - /code/modules/weko-groups/weko_groups.egg-info
    - /code/modules/weko-search-ui/weko_search_ui.egg-info
    - /code/modules/weko-records/weko_records.egg-info
    - /code/modules/weko-records-ui/weko_records_ui.egg-info
    - /code/modules/weko-schema-ui/weko_schema_ui.egg-info
    - /code/modules/weko-index-tree/weko_index_tree.egg-info
    - /code/modules/weko-user-profiles/weko_user_profiles.egg-info
    - /code/modules/weko-deposit/weko_deposit.egg-info
    - /code/modules/weko-authors/weko_authors.egg-info
    - /code/modules/weko-plugins/weko_plugins.egg-info
    - /code/modules/weko-workflow/weko_workflow.egg-info
    - .:/code
  user: invenio

clamav:
  restart: "always"
  image: mkodockx/docker-clamav
  ports:
    - "3306:3310"

